const { __ } = wp.i18n;
import containerBlockIcons from "../container-block-icons";

const containerBlockVariations = [
    {
        key: "layout_1",
        // name: __("Layout 1", "responsive-block-editor-addons"),
        // title: __("Layout 1", "responsive-block-editor-addons"),
        // description: __("Layout 1", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_1,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-1",
    },
    {
        key: "layout_2",
        // name: __("Layout 2", "responsive-block-editor-addons"),
        // title: __("Layout 2", "responsive-block-editor-addons"),
        // description: __("Layout 2", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_2,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-2",
    },
    {
        key: "layout_3",
        // name: __("Layout 3", "responsive-block-editor-addons"),
        // title: __("Layout 3", "responsive-block-editor-addons"),
        // description: __("Layout 3", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_3,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-3",
    },
    {
        key: "layout_4",
        // name: __("Layout 4", "responsive-block-editor-addons"),
        // title: __("Layout 4", "responsive-block-editor-addons"),
        // description: __("Layout 4", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_4,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-4",
    },

    //TODO
    {
        key: "layout_5",
        // name: __("Layout 5", "responsive-block-editor-addons"),
        // title: __("Layout 5", "responsive-block-editor-addons"),
        // description: __("Layout 5", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_5,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-5",
    },
    {
        key: "layout_6",
        // name: __("Layout 6", "responsive-block-editor-addons"),
        // title: __("Layout 6", "responsive-block-editor-addons"),
        // description: __("Layout 6", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_6,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-6",
    },
    {
        key: "layout_7",
        // name: __("Layout 7", "responsive-block-editor-addons"),
        // title: __("Layout 7", "responsive-block-editor-addons"),
        // description: __("Layout 7", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_7,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-7",
    },
    {
        key: "layout_8",
        // name: __("Layout 8", "responsive-block-editor-addons"),
        // title: __("Layout 8", "responsive-block-editor-addons"),
        // description: __("Layout 8", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_8,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-8",
    },
    {
        key: "layout_9",
        // name: __("Layout 9", "responsive-block-editor-addons"),
        // title: __("Layout 9", "responsive-block-editor-addons"),
        // description: __("Layout 9", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_9,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-9",
    },
    {
        key: "layout_10",
        // name: __("Layout 10", "responsive-block-editor-addons"),
        // title: __("Layout 10", "responsive-block-editor-addons"),
        // description: __("Layout 10", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_10,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-10",
    },
    {
        key: "layout_11",
        // name: __("Layout 11", "responsive-block-editor-addons"),
        // title: __("Layout 11", "responsive-block-editor-addons"),
        // description: __("Layout 11", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_11,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-11",
    },
    {
        key: "layout_12",
        // name: __("Layout 12", "responsive-block-editor-addons"),
        // title: __("Layout 12", "responsive-block-editor-addons"),
        // description: __("Layout 12", "responsive-block-editor-addons"),
        icon: containerBlockIcons.layout_12,
        innerBlocks: [
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
            ['responsive-block-editor-addons/container-child', {}],
        ],
        scope: [ 'block' ],
        className: "rbea-container-variation-layout-12",
    },
];

export default containerBlockVariations;